server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
<<<<<<< HEAD
<<<<<<< Updated upstream
=======
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
>>>>>>> feature/colegio-frontend
      routes:
        - id: gestion_academica_route
          uri: lb://BUSINESSDOMAIN-GESTION-ACADEMICA
          predicates:
            - Path=/api/v1/academica/**
          filters:
            - AuthenticationFilterinig
            
        - id: asistencia_conducta_route
<<<<<<< HEAD
          uri: lb://businessdomain-asistencia-conducta
=======
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: gestion_academica_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/academica/**
            
        - id: asistencia_conducta_route
          uri: http://localhost:8082
>>>>>>> Stashed changes
=======
          uri: lb://BUSINESSDOMAIN-ASISTENCIA-CONDUCTA 
>>>>>>> feature/colegio-frontend
          predicates:
            - Path=/api/v1/conducta/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka