# ===================================================================
# 1. IDENTIFICACIÓN Y PUERTO
# ===================================================================
server.port=8081
spring.application.name=BUSINESSDOMAIN-GESTION-ACADEMICA
<<<<<<< HEAD

springdoc.swagger-ui.path=/swagger-ui.html

=======
>>>>>>> feature/colegio-frontend
# ===================================================================
# 2. CONEXIÓN AL SERVIDOR EUREKA 
# ===================================================================
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.healthcheck.enabled=true
eureka.client.fetch-registry=true
spring.cloud.config.override-none=false

# ===================================================================
# 3. BASE DE DATOS H2 EN MEMORIA Y SCRIPTS AUTOMÁTICOS
# ===================================================================
<<<<<<< HEAD
spring.datasource.url=jdbc:h2:mem:colegiodb;DB_CLOSE_DELAY=-1
=======
spring.datasource.url=jdbc:h2:mem:colegiodb
>>>>>>> feature/colegio-frontend
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

<<<<<<< HEAD
spring.jpa.hibernate.ddl-auto=create-drop

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=false
=======
# Estrategia de creación: Crea las tablas al iniciar y las destruye al apagar el servidor
spring.jpa.hibernate.ddl-auto=create-drop

# Inicialización de datos: Fuerza la lectura de tu archivo 'import.sql'
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
>>>>>>> feature/colegio-frontend

# ===================================================================
# 4. MONITOREO ACTUATOR
# ===================================================================
management.endpoints.web.exposure.include=*
management.endpoint.info.enabled=true
<<<<<<< HEAD
management.endpoint.health.enabled=true

# ===================================================================
# 5. LOGS DE DIAGNÓSTICO (Añade esto al final)
# ===================================================================
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.jdbc.datasource.init=DEBUG

# ===================================================================
# 6. CONFIGURACIÓN DE CORS PARA SERVIDOR REACTIVO (WEBFLUX)
# ===================================================================
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
=======
management.endpoint.health.enabled=true
>>>>>>> feature/colegio-frontend
